development:
  adapter: postgresql
  database: sNotes_development
  username: shendidy
  encoding: unicode
  host: localhost
  pool: 5
test:
  adapter: postgresql
  database: sNotes_test
  username: shendidy
  encoding: unicode
  host: localhost
  pool: 5
